parser: "babel-eslint"
extends: "airbnb-base"
env:
  mocha: true
  es6: true
  browser: true
rules:
  # Although it can look nice, it can also look a lot more verbose than necessary when forcing spacing around "}".
  "object-curly-spacing": off
  "comma-dangle":
    - error
    - "only-multiline"
  # no-restricted-syntax is adapted from Airbnb style guide, but allows for-in and for-of.
  "no-restricted-syntax":
    - error
    - selector: LabeledStatement
      message: "Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand."
    - selector: WithStatement
      message: "`with` is disallowed in strict mode because it makes code impossible to predict and optimize."
