language: node_js
node_js:
  - '8'
  - '6'
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: build & test
    script:
    - npm run build
    - npm run test
  - stage: deploy docs
    if: branch = master
    node_js: "8"
    script:
    - npm run docs
    - npm run docs-examples
    - echo "Deploying docs to github pages"
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      keep-history: false
      local-dir: docs-out
      on:
        branch: master
