window.esdocSearchIndex = [
  [
    "redapp/es/tracking/accounts/at/index.js~accounts_get_all",
    "variable/index.html#static-variable-ACCOUNTS_GET_ALL",
    "<span>ACCOUNTS_GET_ALL</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/accounts/at/index.js~accounts_poll_error",
    "variable/index.html#static-variable-ACCOUNTS_POLL_ERROR",
    "<span>ACCOUNTS_POLL_ERROR</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/accounts/at/index.js~accounts_start_polling",
    "variable/index.html#static-variable-ACCOUNTS_START_POLLING",
    "<span>ACCOUNTS_START_POLLING</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/accounts/at/index.js~accounts_stop_polling",
    "variable/index.html#static-variable-ACCOUNTS_STOP_POLLING",
    "<span>ACCOUNTS_STOP_POLLING</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/accounts/at/index.js~account_balance",
    "variable/index.html#static-variable-ACCOUNT_BALANCE",
    "<span>ACCOUNT_BALANCE</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/accounts/at/index.js~account_get",
    "variable/index.html#static-variable-ACCOUNT_GET",
    "<span>ACCOUNT_GET</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/accounts/at/index.js~account_get_balance",
    "variable/index.html#static-variable-ACCOUNT_GET_BALANCE",
    "<span>ACCOUNT_GET_BALANCE</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/accounts/at/index.js~account_get_balance_failed",
    "variable/index.html#static-variable-ACCOUNT_GET_BALANCE_FAILED",
    "<span>ACCOUNT_GET_BALANCE_FAILED</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/contracts/at/index.js~add_contract",
    "variable/index.html#static-variable-ADD_CONTRACT",
    "<span>ADD_CONTRACT</span> <span class=\"search-result-import-path\">redapp/es/contracts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/accounts/at/index.js~add_local_account",
    "variable/index.html#static-variable-ADD_LOCAL_ACCOUNT",
    "<span>ADD_LOCAL_ACCOUNT</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~blocks_listen_error",
    "variable/index.html#static-variable-BLOCKS_LISTEN_ERROR",
    "<span>BLOCKS_LISTEN_ERROR</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~blocks_poll_error",
    "variable/index.html#static-variable-BLOCKS_POLL_ERROR",
    "<span>BLOCKS_POLL_ERROR</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~blocks_start_listening",
    "variable/index.html#static-variable-BLOCKS_START_LISTENING",
    "<span>BLOCKS_START_LISTENING</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~blocks_start_polling",
    "variable/index.html#static-variable-BLOCKS_START_POLLING",
    "<span>BLOCKS_START_POLLING</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~blocks_stop_listening",
    "variable/index.html#static-variable-BLOCKS_STOP_LISTENING",
    "<span>BLOCKS_STOP_LISTENING</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~blocks_stop_polling",
    "variable/index.html#static-variable-BLOCKS_STOP_POLLING",
    "<span>BLOCKS_STOP_POLLING</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~blocks_sub_new_block_check",
    "variable/index.html#static-variable-BLOCKS_SUB_NEW_BLOCK_CHECK",
    "<span>BLOCKS_SUB_NEW_BLOCK_CHECK</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~block_failed",
    "variable/index.html#static-variable-BLOCK_FAILED",
    "<span>BLOCK_FAILED</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~block_processed",
    "variable/index.html#static-variable-BLOCK_PROCESSED",
    "<span>BLOCK_PROCESSED</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~block_received",
    "variable/index.html#static-variable-BLOCK_RECEIVED",
    "<span>BLOCK_RECEIVED</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~block_retrieval_error",
    "variable/index.html#static-variable-BLOCK_RETRIEVAL_ERROR",
    "<span>BLOCK_RETRIEVAL_ERROR</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/calls/at/index.js~cache_call",
    "variable/index.html#static-variable-CACHE_CALL",
    "<span>CACHE_CALL</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/calls/at/index.js~call_decode_fail",
    "variable/index.html#static-variable-CALL_DECODE_FAIL",
    "<span>CALL_DECODE_FAIL</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/calls/at/index.js~call_decode_success",
    "variable/index.html#static-variable-CALL_DECODE_SUCCESS",
    "<span>CALL_DECODE_SUCCESS</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/calls/at/index.js~call_failed",
    "variable/index.html#static-variable-CALL_FAILED",
    "<span>CALL_FAILED</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/calls/at/index.js~call_returned",
    "variable/index.html#static-variable-CALL_RETURNED",
    "<span>CALL_RETURNED</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/calls/at/index.js~clear_cache",
    "variable/index.html#static-variable-CLEAR_CACHE",
    "<span>CLEAR_CACHE</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/contracts/at/index.js~contract_added",
    "variable/index.html#static-variable-CONTRACT_ADDED",
    "<span>CONTRACT_ADDED</span> <span class=\"search-result-import-path\">redapp/es/contracts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/calls/at/index.js~force_call",
    "variable/index.html#static-variable-FORCE_CALL",
    "<span>FORCE_CALL</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/calls/at/index.js~forget_call",
    "variable/index.html#static-variable-FORGET_CALL",
    "<span>FORGET_CALL</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/contracts/at/index.js~forget_contract",
    "variable/index.html#static-variable-FORGET_CONTRACT",
    "<span>FORGET_CONTRACT</span> <span class=\"search-result-import-path\">redapp/es/contracts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/accounts/at/index.js~forget_local_account",
    "variable/index.html#static-variable-FORGET_LOCAL_ACCOUNT",
    "<span>FORGET_LOCAL_ACCOUNT</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/transactions/at/index.js~forget_tx",
    "variable/index.html#static-variable-FORGET_TX",
    "<span>FORGET_TX</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~get_block",
    "variable/index.html#static-variable-GET_BLOCK",
    "<span>GET_BLOCK</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/blocks/at/index.js~get_latest_block",
    "variable/index.html#static-variable-GET_LATEST_BLOCK",
    "<span>GET_LATEST_BLOCK</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/transactions/at/index.js~send_tx",
    "variable/index.html#static-variable-SEND_TX",
    "<span>SEND_TX</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/transactions/at/index.js~send_tx_failed",
    "variable/index.html#static-variable-SEND_TX_FAILED",
    "<span>SEND_TX_FAILED</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/transactions/at/index.js~tx_broadcast",
    "variable/index.html#static-variable-TX_BROADCAST",
    "<span>TX_BROADCAST</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/transactions/at/index.js~tx_failed",
    "variable/index.html#static-variable-TX_FAILED",
    "<span>TX_FAILED</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/transactions/at/index.js~tx_final",
    "variable/index.html#static-variable-TX_FINAL",
    "<span>TX_FINAL</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/transactions/at/index.js~tx_receipt",
    "variable/index.html#static-variable-TX_RECEIPT",
    "<span>TX_RECEIPT</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/transactions/at/index.js~tx_sent",
    "variable/index.html#static-variable-TX_SENT",
    "<span>TX_SENT</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/AT/index.js</span>",
    "variable"
  ],
  [
    "redapp/es/contracts/actions/index.js~addcontract",
    "function/index.html#static-function-addContract",
    "<span>addContract</span> <span class=\"search-result-import-path\">redapp/es/contracts/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/accounts/actions/index.js~addlocalacount",
    "function/index.html#static-function-addLocalAcount",
    "<span>addLocalAcount</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/calls/awaitcall.js~awaitcall",
    "function/index.html#static-function-awaitCall",
    "<span>awaitCall</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/awaitCall.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/blocks/blockssaga.js~blockssaga",
    "function/index.html#static-function-blocksSaga",
    "<span>blocksSaga</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/blocksSaga.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/calls/actions/index.js~cachecall",
    "function/index.html#static-function-cacheCall",
    "<span>cacheCall</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/calls/callssaga.js~callssaga",
    "function/index.html#static-function-callsSaga",
    "<span>callsSaga</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/callsSaga.js</span>",
    "function"
  ],
  [
    "redapp/es/contracts/contractssaga.js~contractssaga",
    "function/index.html#static-function-contractsSaga",
    "<span>contractsSaga</span> <span class=\"search-result-import-path\">redapp/es/contracts/contractsSaga.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/transactions/transactionssaga.js~createtransactionpromievent",
    "function/index.html#static-function-createTransactionPromiEvent",
    "<span>createTransactionPromiEvent</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/transactionsSaga.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/accounts/actions/index.js~fetchallacounts",
    "function/index.html#static-function-fetchAllAcounts",
    "<span>fetchAllAcounts</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/calls/actions/index.js~forcecall",
    "function/index.html#static-function-forceCall",
    "<span>forceCall</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/calls/actions/index.js~forgetcall",
    "function/index.html#static-function-forgetCall",
    "<span>forgetCall</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/contracts/actions/index.js~forgetcontract",
    "function/index.html#static-function-forgetContract",
    "<span>forgetContract</span> <span class=\"search-result-import-path\">redapp/es/contracts/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/accounts/actions/index.js~forgetlocalaccount",
    "function/index.html#static-function-forgetLocalAccount",
    "<span>forgetLocalAccount</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/transactions/actions/index.js~forgettx",
    "function/index.html#static-function-forgetTX",
    "<span>forgetTX</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/accounts/actions/index.js~getallaccounts",
    "function/index.html#static-function-getAllAccounts",
    "<span>getAllAccounts</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/accounts/actions/index.js~getbalance",
    "function/index.html#static-function-getBalance",
    "<span>getBalance</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/blocks/actions/index.js~getblock",
    "function/index.html#static-function-getBlock",
    "<span>getBlock</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/blocks/actions/index.js~getlatestblock",
    "function/index.html#static-function-getLatestBlock",
    "<span>getLatestBlock</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/accounts/actions/index.js~getsingleaccount",
    "function/index.html#static-function-getSingleAccount",
    "<span>getSingleAccount</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/blocks/blockssaga.js~getspecificblock",
    "function/index.html#static-function-getSpecificBlock",
    "<span>getSpecificBlock</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/blocksSaga.js</span>",
    "function"
  ],
  [
    "redapp/es/initweb3.js~initweb3",
    "function/index.html#static-function-initWeb3",
    "<span>initWeb3</span> <span class=\"search-result-import-path\">redapp/es/initWeb3.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/calls/callssaga.js~initiatecall",
    "function/index.html#static-function-initiateCall",
    "<span>initiateCall</span> <span class=\"search-result-import-path\">redapp/es/tracking/calls/callsSaga.js</span>",
    "function"
  ],
  [
    "redapp/es/util/mapped-reducer.js~mappedreducer",
    "function/index.html#static-function-mappedreducer",
    "<span>mappedreducer</span> <span class=\"search-result-import-path\">redapp/es/util/mapped-reducer.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/transactions/opentxchannel.js~opentxchannel",
    "function/index.html#static-function-openTxChannel",
    "<span>openTxChannel</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/openTxChannel.js</span>",
    "function"
  ],
  [
    "redapp/es/util/poller.js~poller",
    "function/index.html#static-function-poller",
    "<span>poller</span> <span class=\"search-result-import-path\">redapp/es/util/poller.js</span>",
    "function"
  ],
  [
    "redapp/es/reducer.js~reducer",
    "variable/index.html#static-variable-reducer",
    "<span>reducer</span> <span class=\"search-result-import-path\">redapp/es/reducer.js</span>",
    "variable"
  ],
  [
    "redapp/es/saga.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">redapp/es/saga.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/transactions/actions/index.js~sendtx",
    "function/index.html#static-function-sendTX",
    "<span>sendTX</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/accounts/actions/index.js~startaccountpolling",
    "function/index.html#static-function-startAccountPolling",
    "<span>startAccountPolling</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/blocks/actions/index.js~startblocklistening",
    "function/index.html#static-function-startBlockListening",
    "<span>startBlockListening</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/blocks/actions/index.js~startblockpolling",
    "function/index.html#static-function-startBlockPolling",
    "<span>startBlockPolling</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/accounts/actions/index.js~stopaccountpolling",
    "function/index.html#static-function-stopAccountPolling",
    "<span>stopAccountPolling</span> <span class=\"search-result-import-path\">redapp/es/tracking/accounts/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/blocks/actions/index.js~stopblocklistening",
    "function/index.html#static-function-stopBlockListening",
    "<span>stopBlockListening</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/blocks/actions/index.js~stopblockpolling",
    "function/index.html#static-function-stopBlockPolling",
    "<span>stopBlockPolling</span> <span class=\"search-result-import-path\">redapp/es/tracking/blocks/actions/index.js</span>",
    "function"
  ],
  [
    "redapp/es/util/subber.js~subber",
    "function/index.html#static-function-subber",
    "<span>subber</span> <span class=\"search-result-import-path\">redapp/es/util/subber.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/trackingred.js~trackingred",
    "variable/index.html#static-variable-trackingRed",
    "<span>trackingRed</span> <span class=\"search-result-import-path\">redapp/es/tracking/trackingRed.js</span>",
    "variable"
  ],
  [
    "redapp/es/tracking/trackingsaga.js~trackingsaga",
    "function/index.html#static-function-trackingSaga",
    "<span>trackingSaga</span> <span class=\"search-result-import-path\">redapp/es/tracking/trackingSaga.js</span>",
    "function"
  ],
  [
    "redapp/es/tracking/transactions/transactionssaga.js~transactionssaga",
    "function/index.html#static-function-transactionsSaga",
    "<span>transactionsSaga</span> <span class=\"search-result-import-path\">redapp/es/tracking/transactions/transactionsSaga.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/contracts/at/index.js",
    "file/src/contracts/AT/index.js.html",
    "src/contracts/AT/index.js",
    "file"
  ],
  [
    "src/contracts/actions/index.js",
    "file/src/contracts/actions/index.js.html",
    "src/contracts/actions/index.js",
    "file"
  ],
  [
    "src/contracts/contractsred.js",
    "file/src/contracts/contractsRed.js.html",
    "src/contracts/contractsRed.js",
    "file"
  ],
  [
    "src/contracts/contractssaga.js",
    "file/src/contracts/contractsSaga.js.html",
    "src/contracts/contractsSaga.js",
    "file"
  ],
  [
    "src/docs.js",
    "file/src/docs.js.html",
    "src/docs.js",
    "file"
  ],
  [
    "src/docs.js~reduxactiontype",
    "typedef/index.html#static-typedef-ReduxActionType",
    "src/docs.js~ReduxActionType",
    "typedef"
  ],
  [
    "src/docs.js~reduxreducer",
    "typedef/index.html#static-typedef-ReduxReducer",
    "src/docs.js~ReduxReducer",
    "typedef"
  ],
  [
    "src/docs.js~reduxsaga",
    "typedef/index.html#static-typedef-ReduxSaga",
    "src/docs.js~ReduxSaga",
    "typedef"
  ],
  [
    "src/docs.js~reduxstateselector",
    "typedef/index.html#static-typedef-ReduxStateSelector",
    "src/docs.js~ReduxStateSelector",
    "typedef"
  ],
  [
    "src/docs.js~reduxthunk",
    "typedef/index.html#static-typedef-ReduxThunk",
    "src/docs.js~ReduxThunk",
    "typedef"
  ],
  [
    "src/errors/encodeabierror.js",
    "file/src/errors/EncodeABIError.js.html",
    "src/errors/EncodeABIError.js",
    "file"
  ],
  [
    "src/initweb3.js",
    "file/src/initWeb3.js.html",
    "src/initWeb3.js",
    "file"
  ],
  [
    "src/reducer.js",
    "file/src/reducer.js.html",
    "src/reducer.js",
    "file"
  ],
  [
    "src/saga.js",
    "file/src/saga.js.html",
    "src/saga.js",
    "file"
  ],
  [
    "src/tracking/accounts/at/index.js",
    "file/src/tracking/accounts/AT/index.js.html",
    "src/tracking/accounts/AT/index.js",
    "file"
  ],
  [
    "src/tracking/accounts/accountsred.js",
    "file/src/tracking/accounts/accountsRed.js.html",
    "src/tracking/accounts/accountsRed.js",
    "file"
  ],
  [
    "src/tracking/accounts/accountssaga.js",
    "file/src/tracking/accounts/accountsSaga.js.html",
    "src/tracking/accounts/accountsSaga.js",
    "file"
  ],
  [
    "src/tracking/accounts/actions/index.js",
    "file/src/tracking/accounts/actions/index.js.html",
    "src/tracking/accounts/actions/index.js",
    "file"
  ],
  [
    "src/tracking/blocks/at/index.js",
    "file/src/tracking/blocks/AT/index.js.html",
    "src/tracking/blocks/AT/index.js",
    "file"
  ],
  [
    "src/tracking/blocks/actions/index.js",
    "file/src/tracking/blocks/actions/index.js.html",
    "src/tracking/blocks/actions/index.js",
    "file"
  ],
  [
    "src/tracking/blocks/blocksred.js",
    "file/src/tracking/blocks/blocksRed.js.html",
    "src/tracking/blocks/blocksRed.js",
    "file"
  ],
  [
    "src/tracking/blocks/blockssaga.js",
    "file/src/tracking/blocks/blocksSaga.js.html",
    "src/tracking/blocks/blocksSaga.js",
    "file"
  ],
  [
    "src/tracking/calls/at/index.js",
    "file/src/tracking/calls/AT/index.js.html",
    "src/tracking/calls/AT/index.js",
    "file"
  ],
  [
    "src/tracking/calls/actions/index.js",
    "file/src/tracking/calls/actions/index.js.html",
    "src/tracking/calls/actions/index.js",
    "file"
  ],
  [
    "src/tracking/calls/awaitcall.js",
    "file/src/tracking/calls/awaitCall.js.html",
    "src/tracking/calls/awaitCall.js",
    "file"
  ],
  [
    "src/tracking/calls/callsred.js",
    "file/src/tracking/calls/callsRed.js.html",
    "src/tracking/calls/callsRed.js",
    "file"
  ],
  [
    "src/tracking/calls/callssaga.js",
    "file/src/tracking/calls/callsSaga.js.html",
    "src/tracking/calls/callsSaga.js",
    "file"
  ],
  [
    "src/tracking/trackingred.js",
    "file/src/tracking/trackingRed.js.html",
    "src/tracking/trackingRed.js",
    "file"
  ],
  [
    "src/tracking/trackingsaga.js",
    "file/src/tracking/trackingSaga.js.html",
    "src/tracking/trackingSaga.js",
    "file"
  ],
  [
    "src/tracking/transactions/at/index.js",
    "file/src/tracking/transactions/AT/index.js.html",
    "src/tracking/transactions/AT/index.js",
    "file"
  ],
  [
    "src/tracking/transactions/actions/index.js",
    "file/src/tracking/transactions/actions/index.js.html",
    "src/tracking/transactions/actions/index.js",
    "file"
  ],
  [
    "src/tracking/transactions/opentxchannel.js",
    "file/src/tracking/transactions/openTxChannel.js.html",
    "src/tracking/transactions/openTxChannel.js",
    "file"
  ],
  [
    "src/tracking/transactions/transactionsred.js",
    "file/src/tracking/transactions/transactionsRed.js.html",
    "src/tracking/transactions/transactionsRed.js",
    "file"
  ],
  [
    "src/tracking/transactions/transactionssaga.js",
    "file/src/tracking/transactions/transactionsSaga.js.html",
    "src/tracking/transactions/transactionsSaga.js",
    "file"
  ],
  [
    "src/util/mapped-reducer.js",
    "file/src/util/mapped-reducer.js.html",
    "src/util/mapped-reducer.js",
    "file"
  ],
  [
    "src/util/poller.js",
    "file/src/util/poller.js.html",
    "src/util/poller.js",
    "file"
  ],
  [
    "src/util/subber.js",
    "file/src/util/subber.js.html",
    "src/util/subber.js",
    "file"
  ]
]